name: 'Publish'
on:
    push:
        branches:
            - main
            - beta
concurrency:
    group: publish-${{ github.ref }}
    cancel-in-progress: false
permissions:
    contents: write
    id-token: write
    pull-requests: write
    issues: write
jobs:
    publish:
        name: 'Publish'
        runs-on: ubuntu-latest
        env:
            HUSKY: '0'
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - uses: ./.github/actions/validate
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            - uses: codecov/codecov-action@v5
              with:
                  files: coverage/lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}
